version: "2"

services:
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root-password
        # TODO: Figure out mounted volumes that work via Docker Toolbox
        # (probably just need the right permissions on the directories)
        # volumes:
        #     - "./mysql:/var/lib/mysql"


    wordpress:
        image: wordpress
        links:
            - "db:mysql"
        ports:
            - "8001:80"
        environment:
            MYSQL_PORT_3306_TCP: "true"
            WORDPRESS_DB_PASSWORD: root-password

    joomla:
        image: joomla
        links:
            - "db:mysql"
        ports:
            - "8002:80"
        environment:
            MYSQL_PORT_3306_TCP: "true"
            JOOMLA_DB_PASSWORD: root-password

    drupal:
        image: drupal
        ports:
            - "8003:80"

    ghost:
        image: ghost
        ports:
            - "8004:2368"


volumes: {}
